services:
  mongodb:
    container_name: ${MONGODB_NAME}
    image: mongo:${MONGODB_IMAGE_VERSION}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    restart: always
    volumes:
      - ${MONGODB_VOLUME_PATH}:/data/db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge
